package ca.sharvey.reddit.task;

public enum Type {
	CRAWL, PROCESS, CRAWL_AUTHOR, CRAWL_POST, CRAWL_SUBREDDIT, CRAWL_COMMENT, CRAWL_LISTING, PROCESS_AUTHOR, PROCESS_POST, PROCESS_SUBREDDIT, PROCESS_COMMENT, PROCESS_LISTING
}
